services:
  - type: web
    name: acai-rapidola
    env: node
    buildCommand: npm install && cd server && npm install && cd ../client && npm install && rm -rf dist && npm run build
    startCommand: node server/src/index.js
    envVars:
      - key: DATA_DIR
        value: /data
      - key: MERCADO_PAGO_ACCESS_TOKEN
        sync: false
      - key: APP_URL
        value: https://pedeacai.dream2app.com.br
      - key: MERCADO_PAGO_PUBLIC_KEY
        sync: false
      - key: MP_WEBHOOK_SECRET
        sync: false
      - key: SUPABASE_URL
        value: https://bfjpvexbcjtyidhqokuo.supabase.co
      - key: SUPABASE_SERVICE_ROLE
        sync: false
    disk:
      name: data
      mountPath: /data
      sizeGB: 1
